// AUTO-GENERATED by data/scripts/compile_book_wrappers.py
using System.Collections.Generic;

namespace Koine.Infrastructure.Data.Seed
{
    public static class ThirdJohnTextData
    {
        public static Dictionary<int, List<object>> GetChapters()
        {
            return new Dictionary<int, List<object>>
            {
                { 1, GetChapter1() },
            };
        }

        private static List<object> GetChapter1()
        {
            // Compiled ranges: 1-8, 9-14
            return new List<object>
            {
                // Verse 1
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "SUBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "Ὁ", Transliteration = "Ho", Gloss = "the", GrammarCodes = new List<string> { "ART", "NOM", "M", "S" }, PartOfSpeech = "art" },
                                new Word { Greek = "πρεσβύτερος", Transliteration = "presbyteros", Gloss = "elder", GrammarCodes = new List<string> { "ADJ", "NOM", "M", "S" }, PartOfSpeech = "adj" }
                            },
                            Translation = "The elder"
                        },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "IND_OBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "Γαΐῳ", Transliteration = "Gaiō", Gloss = "to Gaius", GrammarCodes = new List<string> { "N", "DAT", "M", "S" }, PartOfSpeech = "n" },
                                new Word { Greek = "τῷ", Transliteration = "tō", Gloss = "the", GrammarCodes = new List<string> { "ART", "DAT", "M", "S" }, PartOfSpeech = "art" },
                                new Word { Greek = "ἀγαπητῷ", Transliteration = "agapētō", Gloss = "beloved", GrammarCodes = new List<string> { "ADJ", "DAT", "M", "S" }, PartOfSpeech = "adj" }
                            },
                            Translation = "to Gaius the beloved"
                        },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "REL_CLAUSE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ὃν", Transliteration = "hon", Gloss = "whom", GrammarCodes = new List<string> { "PRON", "ACC", "M", "S" }, PartOfSpeech = "pron" },
                                new Word { Greek = "ἐγὼ", Transliteration = "egō", Gloss = "I", GrammarCodes = new List<string> { "PRON", "NOM", "1P", "S" }, PartOfSpeech = "pron" },
                                new Word { Greek = "ἀγαπῶ", Transliteration = "agapō", Gloss = "love", GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "1P", "S" }, PartOfSpeech = "v" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "PREP_PHRASE" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "ἐν", Transliteration = "en", Gloss = "in", GrammarCodes = new List<string> { "PREP" }, PartOfSpeech = "prep" },
                                        new Word { Greek = "ἀληθείᾳ", Transliteration = "alētheia", Gloss = "truth", GrammarCodes = new List<string> { "N", "DAT", "F", "S" }, PartOfSpeech = "n" }
                                    },
                                    Translation = "in truth"
                                }
                            },
                            Translation = "whom I love in truth"
                        }
                    },
                    Translation = "The elder to Gaius the beloved, whom I love in truth."
                },

                // Verse 2
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "Ἀγαπητέ", Transliteration = "Agapēte", Gloss = "Beloved", GrammarCodes = new List<string> { "ADJ", "VOC", "M", "S" }, PartOfSpeech = "adj" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PREP_PHRASE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "περὶ", Transliteration = "peri", Gloss = "concerning", GrammarCodes = new List<string> { "PREP" }, PartOfSpeech = "prep" },
                                new Word { Greek = "πάντων", Transliteration = "pantōn", Gloss = "all things", GrammarCodes = new List<string> { "ADJ", "GEN", "N", "P" }, PartOfSpeech = "adj" }
                            },
                            Translation = "concerning all things"
                        },
                        new Word { Greek = "εὔχομαί", Transliteration = "euchomai", Gloss = "I pray", GrammarCodes = new List<string> { "V", "PRES", "MID", "IND", "1P", "S" }, PartOfSpeech = "v" },
                        new Word { Greek = "σε", Transliteration = "se", Gloss = "you", GrammarCodes = new List<string> { "PRON", "ACC", "2P", "S" }, PartOfSpeech = "pron" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "INF_PHRASE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "εὐοδοῦσθαι", Transliteration = "euodousthai", Gloss = "to prosper", GrammarCodes = new List<string> { "V", "PRES", "PASS", "INF" }, PartOfSpeech = "v" },
                                new Word { Greek = "καὶ", Transliteration = "kai", Gloss = "and", GrammarCodes = new List<string> { "CONJ" }, PartOfSpeech = "conj" },
                                new Word { Greek = "ὑγιαίνειν", Transliteration = "hygiainein", Gloss = "to be in health", GrammarCodes = new List<string> { "V", "PRES", "ACT", "INF" }, PartOfSpeech = "v" }
                            },
                            Translation = "to prosper and to be in health"
                        },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "DEP_CLAUSE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "καθὼς", Transliteration = "kathōs", Gloss = "just as", GrammarCodes = new List<string> { "ADV" }, PartOfSpeech = "adv" },
                                new Word { Greek = "εὐοδοῦταί", Transliteration = "euodoutai", Gloss = "prospers", GrammarCodes = new List<string> { "V", "PRES", "PASS", "IND", "3P", "S" }, PartOfSpeech = "v" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "NOUN_PHRASE", "SUBJ" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "σου", Transliteration = "sou", Gloss = "your", GrammarCodes = new List<string> { "PRON", "GEN", "2P", "S" }, PartOfSpeech = "pron" },
                                        new Word { Greek = "ἡ", Transliteration = "hē", Gloss = "the", GrammarCodes = new List<string> { "ART", "NOM", "F", "S" }, PartOfSpeech = "art" },
                                        new Word { Greek = "ψυχή", Transliteration = "psychē", Gloss = "soul", GrammarCodes = new List<string> { "N", "NOM", "F", "S" }, PartOfSpeech = "n" }
                                    },
                                    Translation = "your soul"
                                }
                            },
                            Translation = "just as your soul prospers"
                        }
                    },
                    Translation = "Beloved, I pray that in all things you may prosper and be in health, just as your soul prospers."
                },

                // Verse 3
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "ἐχάρην", Transliteration = "echarēn", Gloss = "I rejoiced", GrammarCodes = new List<string> { "V", "AOR", "PASS", "IND", "1P", "S" }, PartOfSpeech = "v" },
                        new Word { Greek = "γὰρ", Transliteration = "gar", Gloss = "for", GrammarCodes = new List<string> { "CONJ" }, PartOfSpeech = "conj" },
                        new Word { Greek = "λίαν", Transliteration = "lian", Gloss = "greatly", GrammarCodes = new List<string> { "ADV" }, PartOfSpeech = "adv" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "GEN_ABS" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ἐρχομένων", Transliteration = "erchomenōn", Gloss = "coming", GrammarCodes = new List<string> { "V", "PRES", "MID", "PTCP", "GEN", "M", "P" }, PartOfSpeech = "v" },
                                new Word { Greek = "ἀδελφῶν", Transliteration = "adelphōn", Gloss = "brothers", GrammarCodes = new List<string> { "N", "GEN", "M", "P" }, PartOfSpeech = "n" },
                                new Word { Greek = "καὶ", Transliteration = "kai", Gloss = "and", GrammarCodes = new List<string> { "CONJ" }, PartOfSpeech = "conj" },
                                new Word { Greek = "μαρτυρούντων", Transliteration = "martyrountōn", Gloss = "testifying", GrammarCodes = new List<string> { "V", "PRES", "ACT", "PTCP", "GEN", "M", "P" }, PartOfSpeech = "v" },
                                new Word { Greek = "σου", Transliteration = "sou", Gloss = "to your", GrammarCodes = new List<string> { "PRON", "GEN", "2P", "S" }, PartOfSpeech = "pron" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "NOUN_PHRASE" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "τῇ", Transliteration = "tē", Gloss = "the", GrammarCodes = new List<string> { "ART", "DAT", "F", "S" }, PartOfSpeech = "art" },
                                        new Word { Greek = "ἀληθείᾳ", Transliteration = "alētheia", Gloss = "truth", GrammarCodes = new List<string> { "N", "DAT", "F", "S" }, PartOfSpeech = "n" }
                                    },
                                    Translation = "truth"
                                }
                            },
                            Translation = "when the brothers came and testified to your truth"
                        },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "DEP_CLAUSE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "καθὼς", Transliteration = "kathōs", Gloss = "just as", GrammarCodes = new List<string> { "ADV" }, PartOfSpeech = "adv" },
                                new Word { Greek = "σὺ", Transliteration = "sy", Gloss = "you", GrammarCodes = new List<string> { "PRON", "NOM", "2P", "S" }, PartOfSpeech = "pron" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "PREP_PHRASE" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "ἐν", Transliteration = "en", Gloss = "in", GrammarCodes = new List<string> { "PREP" }, PartOfSpeech = "prep" },
                                        new Word { Greek = "ἀληθείᾳ", Transliteration = "alētheia", Gloss = "truth", GrammarCodes = new List<string> { "N", "DAT", "F", "S" }, PartOfSpeech = "n" }
                                    },
                                    Translation = "in truth"
                                },
                                new Word { Greek = "περιπατεῖς", Transliteration = "peripateis", Gloss = "walk", GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "2P", "S" }, PartOfSpeech = "v" }
                            },
                            Translation = "as you walk in truth"
                        }
                    },
                    Translation = "For I rejoiced greatly when the brothers came and testified to your truth, just as you walk in truth."
                },

                // Verse 4
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "OBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "μειζοτέραν", Transliteration = "meizoteran", Gloss = "greater", GrammarCodes = new List<string> { "ADJ", "ACC", "F", "S" }, PartOfSpeech = "adj" },
                                new Word { Greek = "τούτων", Transliteration = "toutōn", Gloss = "than these", GrammarCodes = new List<string> { "PRON", "GEN", "N", "P" }, PartOfSpeech = "pron" }
                            },
                            Translation = "greater than these"
                        },
                        new Word { Greek = "οὐκ", Transliteration = "ouk", Gloss = "not", GrammarCodes = new List<string> { "PART" }, PartOfSpeech = "part" },
                        new Word { Greek = "ἔχω", Transliteration = "echō", Gloss = "I have", GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "1P", "S" }, PartOfSpeech = "v" },
                        new Word { Greek = "χαράν", Transliteration = "charan", Gloss = "joy", GrammarCodes = new List<string> { "N", "ACC", "F", "S" }, PartOfSpeech = "n" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PURPOSE_CLAUSE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ἵνα", Transliteration = "hina", Gloss = "that", GrammarCodes = new List<string> { "CONJ" }, PartOfSpeech = "conj" },
                                new Word { Greek = "ἀκούω", Transliteration = "akouō", Gloss = "I may hear", GrammarCodes = new List<string> { "V", "PRES", "ACT", "SUBJ", "1P", "S" }, PartOfSpeech = "v" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "NOUN_PHRASE", "OBJ" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "τὰ", Transliteration = "ta", Gloss = "the", GrammarCodes = new List<string> { "ART", "ACC", "N", "P" }, PartOfSpeech = "art" },
                                        new Word { Greek = "ἐμὰ", Transliteration = "ema", Gloss = "my", GrammarCodes = new List<string> { "ADJ", "ACC", "N", "P" }, PartOfSpeech = "adj" },
                                        new Word { Greek = "τέκνα", Transliteration = "tekna", Gloss = "children", GrammarCodes = new List<string> { "N", "ACC", "N", "P" }, PartOfSpeech = "n" }
                                    },
                                    Translation = "my children"
                                },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "PTCP" },
                                    Content = new List<object>
                                    {
                                        new Phrase
                                        {
                                            SyntaxCodes = new List<string> { "PREP_PHRASE" },
                                            Content = new List<object>
                                            {
                                                new Word { Greek = "ἐν", Transliteration = "en", Gloss = "in", GrammarCodes = new List<string> { "PREP" }, PartOfSpeech = "prep" },
                                                new Word { Greek = "ἀληθείᾳ", Transliteration = "alētheia", Gloss = "truth", GrammarCodes = new List<string> { "N", "DAT", "F", "S" }, PartOfSpeech = "n" }
                                            },
                                            Translation = "in truth"
                                        },
                                        new Word { Greek = "περιπατοῦντα", Transliteration = "peripatounta", Gloss = "walking", GrammarCodes = new List<string> { "V", "PRES", "ACT", "PTCP", "ACC", "N", "P" }, PartOfSpeech = "v" }
                                    },
                                    Translation = "walking in truth"
                                }
                            },
                            Translation = "that I may hear of my children walking in truth"
                        }
                    },
                    Translation = "I have no greater joy than this: to hear that my children are walking in truth."
                },

                // Verse 5
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "Ἀγαπητέ", Transliteration = "Agapēte", Gloss = "Beloved", GrammarCodes = new List<string> { "ADJ", "VOC", "M", "S" }, PartOfSpeech = "adj" },
                        new Word { Greek = "πιστὸν", Transliteration = "piston", Gloss = "faithfully", GrammarCodes = new List<string> { "ADJ", "ACC", "N", "S" }, PartOfSpeech = "adj" },
                        new Word { Greek = "ποιεῖς", Transliteration = "poieis", Gloss = "you do", GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "2P", "S" }, PartOfSpeech = "v" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "REL_CLAUSE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ὃ", Transliteration = "ho", Gloss = "whatever", GrammarCodes = new List<string> { "PRON", "ACC", "N", "S" }, PartOfSpeech = "pron" },
                                new Word { Greek = "ἐὰν", Transliteration = "ean", Gloss = "ever", GrammarCodes = new List<string> { "PART" }, PartOfSpeech = "part" },
                                new Word { Greek = "ἐργάσῃ", Transliteration = "ergasē", Gloss = "you work", GrammarCodes = new List<string> { "V", "AOR", "MID", "SUBJ", "2P", "S" }, PartOfSpeech = "v" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "PREP_PHRASE" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "εἰς", Transliteration = "eis", Gloss = "for", GrammarCodes = new List<string> { "PREP" }, PartOfSpeech = "prep" },
                                        new Phrase
                                        {
                                            SyntaxCodes = new List<string> { "NOUN_PHRASE" },
                                            Content = new List<object>
                                            {
                                                new Word { Greek = "τοὺς", Transliteration = "tous", Gloss = "the", GrammarCodes = new List<string> { "ART", "ACC", "M", "P" }, PartOfSpeech = "art" },
                                                new Word { Greek = "ἀδελφοὺς", Transliteration = "adelphous", Gloss = "brothers", GrammarCodes = new List<string> { "N", "ACC", "M", "P" }, PartOfSpeech = "n" }
                                            },
                                            Translation = "the brothers"
                                        }
                                    },
                                    Translation = "for the brothers"
                                },
                                new Word { Greek = "καὶ", Transliteration = "kai", Gloss = "and", GrammarCodes = new List<string> { "CONJ" }, PartOfSpeech = "conj" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "NOUN_PHRASE" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "τοῦτο", Transliteration = "touto", Gloss = "even", GrammarCodes = new List<string> { "PRON", "ACC", "N", "S" }, PartOfSpeech = "pron" },
                                        new Word { Greek = "ξένους", Transliteration = "xenous", Gloss = "strangers", GrammarCodes = new List<string> { "ADJ", "ACC", "M", "P" }, PartOfSpeech = "adj" }
                                    },
                                    Translation = "especially strangers"
                                }
                            },
                            Translation = "whatever you do for the brothers, and for strangers at that"
                        }
                    },
                    Translation = "Beloved, you act faithfully in whatever you do for the brothers, and especially for strangers."
                },

                // Verse 6
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "REL_CLAUSE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "οἳ", Transliteration = "hoi", Gloss = "who", GrammarCodes = new List<string> { "PRON", "NOM", "M", "P" }, PartOfSpeech = "pron" },
                                new Word { Greek = "ἐμαρτύρησάν", Transliteration = "emartyrēsan", Gloss = "testified", GrammarCodes = new List<string> { "V", "AOR", "ACT", "IND", "3P", "P" }, PartOfSpeech = "v" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "NOUN_PHRASE" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "σου", Transliteration = "sou", Gloss = "to your", GrammarCodes = new List<string> { "PRON", "GEN", "2P", "S" }, PartOfSpeech = "pron" },
                                        new Word { Greek = "τῇ", Transliteration = "tē", Gloss = "the", GrammarCodes = new List<string> { "ART", "DAT", "F", "S" }, PartOfSpeech = "art" },
                                        new Word { Greek = "ἀγάπῃ", Transliteration = "agapē", Gloss = "love", GrammarCodes = new List<string> { "N", "DAT", "F", "S" }, PartOfSpeech = "n" }
                                    },
                                    Translation = "love"
                                },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "PREP_PHRASE" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "ἐνώπιον", Transliteration = "enōpion", Gloss = "before", GrammarCodes = new List<string> { "PREP" }, PartOfSpeech = "prep" },
                                        new Word { Greek = "ἐκκλησίας", Transliteration = "ekklēsias", Gloss = "church", GrammarCodes = new List<string> { "N", "GEN", "F", "S" }, PartOfSpeech = "n" }
                                    },
                                    Translation = "before the church"
                                }
                            },
                            Translation = "who testified to your love before the church"
                        },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "REL_CLAUSE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "οὓς", Transliteration = "hous", Gloss = "whom", GrammarCodes = new List<string> { "PRON", "ACC", "M", "P" }, PartOfSpeech = "pron" },
                                new Word { Greek = "καλῶς", Transliteration = "kalōs", Gloss = "well", GrammarCodes = new List<string> { "ADV" }, PartOfSpeech = "adv" },
                                new Word { Greek = "ποιήσεις", Transliteration = "poiēseis", Gloss = "you will do", GrammarCodes = new List<string> { "V", "FUT", "ACT", "IND", "2P", "S" }, PartOfSpeech = "v" },
                                new Word { Greek = "προπέμψας", Transliteration = "propempsas", Gloss = "having sent forward", GrammarCodes = new List<string> { "V", "AOR", "ACT", "PTCP", "NOM", "M", "S" }, PartOfSpeech = "v" },
                                new Word { Greek = "ἀξίως", Transliteration = "axiōs", Gloss = "worthily", GrammarCodes = new List<string> { "ADV" }, PartOfSpeech = "adv" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "NOUN_PHRASE" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "τοῦ", Transliteration = "tou", Gloss = "of", GrammarCodes = new List<string> { "ART", "GEN", "M", "S" }, PartOfSpeech = "art" },
                                        new Word { Greek = "θεοῦ", Transliteration = "theou", Gloss = "God", GrammarCodes = new List<string> { "N", "GEN", "M", "S" }, PartOfSpeech = "n" }
                                    },
                                    Translation = "of God"
                                }
                            },
                            Translation = "whom you will do well to send forward in a manner worthy of God"
                        }
                    },
                    Translation = "They have testified to your love before the church. You will do well to send them on their journey in a manner worthy of God."
                },

                // Verse 7
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PREP_PHRASE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ὑπὲρ", Transliteration = "hyper", Gloss = "for the sake of", GrammarCodes = new List<string> { "PREP" }, PartOfSpeech = "prep" },
                                new Word { Greek = "γὰρ", Transliteration = "gar", Gloss = "for", GrammarCodes = new List<string> { "CONJ" }, PartOfSpeech = "conj" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "NOUN_PHRASE" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "τοῦ", Transliteration = "tou", Gloss = "the", GrammarCodes = new List<string> { "ART", "GEN", "N", "S" }, PartOfSpeech = "art" },
                                        new Word { Greek = "ὀνόματος", Transliteration = "onomatos", Gloss = "name", GrammarCodes = new List<string> { "N", "GEN", "N", "S" }, PartOfSpeech = "n" }
                                    },
                                    Translation = "the name"
                                }
                            },
                            Translation = "for the sake of the name"
                        },
                        new Word { Greek = "ἐξῆλθον", Transliteration = "exēlthon", Gloss = "they went out", GrammarCodes = new List<string> { "V", "AOR", "ACT", "IND", "3P", "P" }, PartOfSpeech = "v" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PTCP" },
                            Content = new List<object>
                            {
                                new Word { Greek = "μηδὲν", Transliteration = "mēden", Gloss = "nothing", GrammarCodes = new List<string> { "ADJ", "ACC", "N", "S" }, PartOfSpeech = "adj" },
                                new Word { Greek = "λαμβάνοντες", Transliteration = "lambanontes", Gloss = "accepting", GrammarCodes = new List<string> { "V", "PRES", "ACT", "PTCP", "NOM", "M", "P" }, PartOfSpeech = "v" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "PREP_PHRASE" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "ἀπὸ", Transliteration = "apo", Gloss = "from", GrammarCodes = new List<string> { "PREP" }, PartOfSpeech = "prep" },
                                        new Phrase
                                        {
                                            SyntaxCodes = new List<string> { "NOUN_PHRASE" },
                                            Content = new List<object>
                                            {
                                                new Word { Greek = "τῶν", Transliteration = "tōn", Gloss = "the", GrammarCodes = new List<string> { "ART", "GEN", "M", "P" }, PartOfSpeech = "art" },
                                                new Word { Greek = "ἐθνικῶν", Transliteration = "ethnikōn", Gloss = "Gentiles", GrammarCodes = new List<string> { "ADJ", "GEN", "M", "P" }, PartOfSpeech = "adj" }
                                            },
                                            Translation = "the Gentiles"
                                        }
                                    },
                                    Translation = "from the Gentiles"
                                }
                            },
                            Translation = "accepting nothing from the Gentiles"
                        }
                    },
                    Translation = "For they went out for the sake of the name, accepting nothing from the Gentiles."
                },

                // Verse 8
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "SUBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ἡμεῖς", Transliteration = "hēmeis", Gloss = "we", GrammarCodes = new List<string> { "PRON", "NOM", "1P", "P" }, PartOfSpeech = "pron" }
                            },
                            Translation = "we"
                        },
                        new Word { Greek = "οὖν", Transliteration = "oun", Gloss = "therefore", GrammarCodes = new List<string> { "CONJ" }, PartOfSpeech = "conj" },
                        new Word { Greek = "ὀφείλομεν", Transliteration = "opheilomen", Gloss = "ought", GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "1P", "P" }, PartOfSpeech = "v" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "INF_PHRASE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ὑπολαμβάνειν", Transliteration = "hypolambanein", Gloss = "to support", GrammarCodes = new List<string> { "V", "PRES", "ACT", "INF" }, PartOfSpeech = "v" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "NOUN_PHRASE", "OBJ" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "τοὺς", Transliteration = "tous", Gloss = "the", GrammarCodes = new List<string> { "ART", "ACC", "M", "P" }, PartOfSpeech = "art" },
                                        new Word { Greek = "τοιούτους", Transliteration = "toioutous", Gloss = "such men", GrammarCodes = new List<string> { "PRON", "ACC", "M", "P" }, PartOfSpeech = "pron" }
                                    },
                                    Translation = "such men"
                                }
                            },
                            Translation = "to support such men"
                        },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PURPOSE_CLAUSE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ἵνα", Transliteration = "hina", Gloss = "that", GrammarCodes = new List<string> { "CONJ" }, PartOfSpeech = "conj" },
                                new Word { Greek = "συνεργοὶ", Transliteration = "synergoi", Gloss = "fellow workers", GrammarCodes = new List<string> { "ADJ", "NOM", "M", "P" }, PartOfSpeech = "adj" },
                                new Word { Greek = "γινώμεθα", Transliteration = "ginōmetha", Gloss = "we may be", GrammarCodes = new List<string> { "V", "PRES", "MID", "SUBJ", "1P", "P" }, PartOfSpeech = "v" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "NOUN_PHRASE" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "τῇ", Transliteration = "tē", Gloss = "the", GrammarCodes = new List<string> { "ART", "DAT", "F", "S" }, PartOfSpeech = "art" },
                                        new Word { Greek = "ἀληθείᾳ", Transliteration = "alētheia", Gloss = "truth", GrammarCodes = new List<string> { "N", "DAT", "F", "S" }, PartOfSpeech = "n" }
                                    },
                                    Translation = "truth"
                                }
                            },
                            Translation = "that we may be fellow workers for the truth"
                        }
                    },
                    Translation = "Therefore we ought to support such men, so that we may be fellow workers for the truth."
                },

                // Verse 9
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "Ἔγραψά", Transliteration = "Egrapsa", Gloss = "I wrote", 
                            GrammarCodes = new List<string> { "V", "AOR", "ACT", "IND", "1P", "S" }, 
                            PartOfSpeech = "v" },
                        new Word { Greek = "τι", Transliteration = "ti", Gloss = "something", 
                            GrammarCodes = new List<string> { "PRON", "ACC", "N", "S" }, 
                            PartOfSpeech = "part" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PREP_PHRASE", "IND_OBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "τῇ", Transliteration = "tē", Gloss = "the", 
                                    GrammarCodes = new List<string> { "ART", "DAT", "F", "S" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "ἐκκλησίᾳ", Transliteration = "ekklēsia", Gloss = "church", 
                                    GrammarCodes = new List<string> { "N", "DAT", "F", "S" }, 
                                    PartOfSpeech = "n" }
                            },
                            Translation = "to the church"
                        }
                    },
                    Translation = "I wrote something to the church;"
                },
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "ἀλλ᾽", Transliteration = "all'", Gloss = "but", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "SUBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ὁ", Transliteration = "ho", Gloss = "the [one]", 
                                    GrammarCodes = new List<string> { "ART", "NOM", "M", "S" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "φιλοπρωτεύων", Transliteration = "philoprotueōn", Gloss = "loving to be first", 
                                    GrammarCodes = new List<string> { "V", "PRES", "ACT", "PTCP", "NOM", "M", "S" }, 
                                    PartOfSpeech = "v" },
                                new Word { Greek = "αὐτῶν", Transliteration = "autōn", Gloss = "of them", 
                                    GrammarCodes = new List<string> { "PRON", "GEN", "M", "P" }, 
                                    PartOfSpeech = "prep" }
                            },
                            Translation = "the one loving to be first among them"
                        },
                        new Word { Greek = "Διοτρέφης", Transliteration = "Diotrephēs", Gloss = "Diotrephes", 
                            GrammarCodes = new List<string> { "N", "NOM", "M", "S" }, 
                            PartOfSpeech = "n" },
                        new Word { Greek = "οὐκ", Transliteration = "ouk", Gloss = "not", 
                            GrammarCodes = new List<string> { "ADV" }, 
                            PartOfSpeech = "prep" },
                        new Word { Greek = "ἐπιδέχεται", Transliteration = "epidechetai", Gloss = "welcomes", 
                            GrammarCodes = new List<string> { "V", "PRES", "MID", "IND", "3P", "S" }, 
                            PartOfSpeech = "v" },
                        new Word { Greek = "ἡμᾶς", Transliteration = "hēmas", Gloss = "us", 
                            GrammarCodes = new List<string> { "PRON", "ACC", "1P", "P" }, 
                            PartOfSpeech = "prep" }
                    },
                    Translation = "but Diotrephes, who loves to be first among them, does not welcome us."
                },

                // Verse 10
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PREP_PHRASE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "διὰ", Transliteration = "dia", Gloss = "because of", 
                                    GrammarCodes = new List<string> { "PREP" }, 
                                    PartOfSpeech = "prep" },
                                new Word { Greek = "τοῦτο", Transliteration = "touto", Gloss = "this", 
                                    GrammarCodes = new List<string> { "PRON", "ACC", "N", "S" }, 
                                    PartOfSpeech = "adv" }
                            },
                            Translation = "for this reason"
                        },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "COND_CLAUSE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ἐὰν", Transliteration = "ean", Gloss = "if", 
                                    GrammarCodes = new List<string> { "CONJ" }, 
                                    PartOfSpeech = "conj" },
                                new Word { Greek = "ἔλθω", Transliteration = "elthō", Gloss = "I come", 
                                    GrammarCodes = new List<string> { "V", "AOR", "ACT", "SUBJ", "1P", "S" }, 
                                    PartOfSpeech = "v" }
                            },
                            Translation = "if I come"
                        },
                        new Word { Greek = "ὑπομνήσω", Transliteration = "hypomnēsō", Gloss = "I will bring to mind", 
                            GrammarCodes = new List<string> { "V", "FUT", "ACT", "IND", "1P", "S" }, 
                            PartOfSpeech = "v" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "OBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "αὐτοῦ", Transliteration = "autou", Gloss = "his", 
                                    GrammarCodes = new List<string> { "PRON", "GEN", "M", "S" }, 
                                    PartOfSpeech = "prep" },
                                new Word { Greek = "τὰ", Transliteration = "ta", Gloss = "the", 
                                    GrammarCodes = new List<string> { "ART", "ACC", "N", "P" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "ἔργα", Transliteration = "erga", Gloss = "works", 
                                    GrammarCodes = new List<string> { "N", "ACC", "N", "P" }, 
                                    PartOfSpeech = "n" }
                            },
                            Translation = "his works"
                        },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "REL_CLAUSE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ἃ", Transliteration = "ha", Gloss = "which", 
                                    GrammarCodes = new List<string> { "PRON", "ACC", "N", "P" }, 
                                    PartOfSpeech = "pron" },
                                new Word { Greek = "ποιεῖ", Transliteration = "poiei", Gloss = "he does", 
                                    GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "3P", "S" }, 
                                    PartOfSpeech = "v" }
                            },
                            Translation = "which he does"
                        },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PTCP" },
                            Content = new List<object>
                            {
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "NOUN_PHRASE", "DAT_INSTR" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "λόγοις", Transliteration = "logois", Gloss = "with words", 
                                            GrammarCodes = new List<string> { "N", "DAT", "M", "P" }, 
                                            PartOfSpeech = "n" },
                                        new Word { Greek = "πονηροῖς", Transliteration = "ponērois", Gloss = "wicked", 
                                            GrammarCodes = new List<string> { "ADJ", "DAT", "M", "P" }, 
                                            PartOfSpeech = "adj" }
                                    },
                                    Translation = "with wicked words"
                                },
                                new Word { Greek = "φλυαρῶν", Transliteration = "phlyarōn", Gloss = "gossiping against", 
                                    GrammarCodes = new List<string> { "V", "PRES", "ACT", "PTCP", "NOM", "M", "S" }, 
                                    PartOfSpeech = "v" },
                                new Word { Greek = "ἡμᾶς", Transliteration = "hēmas", Gloss = "us", 
                                    GrammarCodes = new List<string> { "PRON", "ACC", "1P", "P" }, 
                                    PartOfSpeech = "prep" }
                            },
                            Translation = "gossiping against us with wicked words"
                        }
                    },
                    Translation = "Therefore, if I come, I will bring to mind his works which he does, gossiping against us with wicked words;"
                },
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "καὶ", Transliteration = "kai", Gloss = "and", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PTCP" },
                            Content = new List<object>
                            {
                                new Word { Greek = "μὴ", Transliteration = "mē", Gloss = "not", 
                                    GrammarCodes = new List<string> { "ADV" }, 
                                    PartOfSpeech = "prep" },
                                new Word { Greek = "ἀρκούμενος", Transliteration = "arkoumenos", Gloss = "being content", 
                                    GrammarCodes = new List<string> { "V", "PRES", "PASS", "PTCP", "NOM", "M", "S" }, 
                                    PartOfSpeech = "v" },
                                new Phrase
                                {
                                    SyntaxCodes = new List<string> { "PREP_PHRASE" },
                                    Content = new List<object>
                                    {
                                        new Word { Greek = "ἐπὶ", Transliteration = "epi", Gloss = "with", 
                                            GrammarCodes = new List<string> { "PREP" }, 
                                            PartOfSpeech = "prep" },
                                        new Word { Greek = "τούτοις", Transliteration = "toutois", Gloss = "these things", 
                                            GrammarCodes = new List<string> { "PRON", "DAT", "N", "P" }, 
                                            PartOfSpeech = "adv" }
                                    },
                                    Translation = "with these things"
                                }
                            },
                            Translation = "and not being content with these things"
                        },
                        new Word { Greek = "οὔτε", Transliteration = "oute", Gloss = "neither", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Word { Greek = "αὐτὸς", Transliteration = "autos", Gloss = "he himself", 
                            GrammarCodes = new List<string> { "PRON", "NOM", "M", "S" }, 
                            PartOfSpeech = "prep" },
                        new Word { Greek = "ἐπιδέχεται", Transliteration = "epidechetai", Gloss = "welcomes", 
                            GrammarCodes = new List<string> { "V", "PRES", "MID", "IND", "3P", "S" }, 
                            PartOfSpeech = "v" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "OBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "τοὺς", Transliteration = "tous", Gloss = "the", 
                                    GrammarCodes = new List<string> { "ART", "ACC", "M", "P" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "ἀδελφοὺς", Transliteration = "adelphous", Gloss = "brothers", 
                                    GrammarCodes = new List<string> { "N", "ACC", "M", "P" }, 
                                    PartOfSpeech = "n" }
                            },
                            Translation = "the brothers"
                        }
                    },
                    Translation = "and not content with these things, he neither welcomes the brothers himself,"
                },
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "καὶ", Transliteration = "kai", Gloss = "and", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "OBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "τοὺς", Transliteration = "tous", Gloss = "the [ones]", 
                                    GrammarCodes = new List<string> { "ART", "ACC", "M", "P" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "βουλομένους", Transliteration = "boulomenous", Gloss = "desiring [to do so]", 
                                    GrammarCodes = new List<string> { "V", "PRES", "MID", "PTCP", "ACC", "M", "P" }, 
                                    PartOfSpeech = "v" }
                            },
                            Translation = "those who desire [to do so]"
                        },
                        new Word { Greek = "κωλύει", Transliteration = "kōlyei", Gloss = "he hinders", 
                            GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "3P", "S" }, 
                            PartOfSpeech = "v" },
                        new Word { Greek = "καὶ", Transliteration = "kai", Gloss = "and", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PREP_PHRASE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ἐκ", Transliteration = "ek", Gloss = "out of", 
                                    GrammarCodes = new List<string> { "PREP" }, 
                                    PartOfSpeech = "prep" },
                                new Word { Greek = "τῆς", Transliteration = "tēs", Gloss = "the", 
                                    GrammarCodes = new List<string> { "ART", "GEN", "F", "S" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "ἐκκλησίας", Transliteration = "ekklēsias", Gloss = "church", 
                                    GrammarCodes = new List<string> { "N", "GEN", "F", "S" }, 
                                    PartOfSpeech = "n" }
                            },
                            Translation = "out of the church"
                        },
                        new Word { Greek = "ἐκβάλλει", Transliteration = "ekballei", Gloss = "he throws [them] out", 
                            GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "3P", "S" }, 
                            PartOfSpeech = "v" }
                    },
                    Translation = "and he hinders those who desire to do so and throws them out of the church."
                },

                // Verse 11
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "Ἀγαπητέ", Transliteration = "Agapēte", Gloss = "Beloved", 
                            GrammarCodes = new List<string> { "ADJ", "VOC", "M", "S" }, 
                            PartOfSpeech = "adj" },
                        new Word { Greek = "μὴ", Transliteration = "mē", Gloss = "not", 
                            GrammarCodes = new List<string> { "ADV" }, 
                            PartOfSpeech = "prep" },
                        new Word { Greek = "μιμοῦ", Transliteration = "mimou", Gloss = "imitate", 
                            GrammarCodes = new List<string> { "V", "PRES", "MID", "IMP", "2P", "S" }, 
                            PartOfSpeech = "v" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "OBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "τὸ", Transliteration = "to", Gloss = "the", 
                                    GrammarCodes = new List<string> { "ART", "ACC", "N", "S" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "κακὸν", Transliteration = "kakon", Gloss = "evil", 
                                    GrammarCodes = new List<string> { "ADJ", "ACC", "N", "S" }, 
                                    PartOfSpeech = "adj" }
                            },
                            Translation = "what is evil"
                        },
                        new Word { Greek = "ἀλλὰ", Transliteration = "alla", Gloss = "but", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "OBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "τὸ", Transliteration = "to", Gloss = "the", 
                                    GrammarCodes = new List<string> { "ART", "ACC", "N", "S" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "ἀγαθόν", Transliteration = "agathon", Gloss = "good", 
                                    GrammarCodes = new List<string> { "ADJ", "ACC", "N", "S" }, 
                                    PartOfSpeech = "adj" }
                            },
                            Translation = "what is good"
                        }
                    },
                    Translation = "Beloved, do not imitate what is evil but what is good."
                },
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "SUBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ὁ", Transliteration = "ho", Gloss = "the [one]", 
                                    GrammarCodes = new List<string> { "ART", "NOM", "M", "S" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "ἀγαθοποιῶν", Transliteration = "agathopoiōn", Gloss = "doing good", 
                                    GrammarCodes = new List<string> { "V", "PRES", "ACT", "PTCP", "NOM", "M", "S" }, 
                                    PartOfSpeech = "v" }
                            },
                            Translation = "the one who does good"
                        },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PREP_PHRASE", "PRED" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ἐκ", Transliteration = "ek", Gloss = "of", 
                                    GrammarCodes = new List<string> { "PREP" }, 
                                    PartOfSpeech = "prep" },
                                new Word { Greek = "τοῦ", Transliteration = "tou", Gloss = "the", 
                                    GrammarCodes = new List<string> { "ART", "GEN", "M", "S" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "θεοῦ", Transliteration = "theou", Gloss = "God", 
                                    GrammarCodes = new List<string> { "N", "GEN", "M", "S" }, 
                                    PartOfSpeech = "n" }
                            },
                            Translation = "is of God"
                        },
                        new Word { Greek = "ἐστιν", Transliteration = "estin", Gloss = "is", 
                            GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "3P", "S" }, 
                            PartOfSpeech = "v" }
                    },
                    Translation = "The one who does good is of God;"
                },
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "SUBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ὁ", Transliteration = "ho", Gloss = "the [one]", 
                                    GrammarCodes = new List<string> { "ART", "NOM", "M", "S" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "κακοποιῶν", Transliteration = "kakopoiōn", Gloss = "doing evil", 
                                    GrammarCodes = new List<string> { "V", "PRES", "ACT", "PTCP", "NOM", "M", "S" }, 
                                    PartOfSpeech = "v" }
                            },
                            Translation = "the one who does evil"
                        },
                        new Word { Greek = "οὐχ", Transliteration = "ouch", Gloss = "not", 
                            GrammarCodes = new List<string> { "ADV" }, 
                            PartOfSpeech = "prep" },
                        new Word { Greek = "ἑώρακεν", Transliteration = "heōraken", Gloss = "has seen", 
                            GrammarCodes = new List<string> { "V", "PERF", "ACT", "IND", "3P", "S" }, 
                            PartOfSpeech = "v" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "OBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "τὸν", Transliteration = "ton", Gloss = "the", 
                                    GrammarCodes = new List<string> { "ART", "ACC", "M", "S" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "θεόν", Transliteration = "theon", Gloss = "God", 
                                    GrammarCodes = new List<string> { "N", "ACC", "M", "S" }, 
                                    PartOfSpeech = "n" }
                            },
                            Translation = "God"
                        }
                    },
                    Translation = "the one who does evil has not seen God."
                },

                // Verse 12
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "Δημητρίῳ", Transliteration = "Dēmētriō", Gloss = "to Demetrius", 
                            GrammarCodes = new List<string> { "N", "DAT", "M", "S" }, 
                            PartOfSpeech = "n" },
                        new Word { Greek = "μεμαρτύρηται", Transliteration = "memartyrētai", Gloss = "it is testified", 
                            GrammarCodes = new List<string> { "V", "PERF", "PASS", "IND", "3P", "S" }, 
                            PartOfSpeech = "v" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PREP_PHRASE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ὑπὸ", Transliteration = "hypo", Gloss = "by", 
                                    GrammarCodes = new List<string> { "PREP" }, 
                                    PartOfSpeech = "prep" },
                                new Word { Greek = "πάντων", Transliteration = "pantōn", Gloss = "all", 
                                    GrammarCodes = new List<string> { "ADJ", "GEN", "M", "P" }, 
                                    PartOfSpeech = "adj" }
                            },
                            Translation = "by all"
                        },
                        new Word { Greek = "καὶ", Transliteration = "kai", Gloss = "and", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PREP_PHRASE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ὑπὸ", Transliteration = "hypo", Gloss = "by", 
                                    GrammarCodes = new List<string> { "PREP" }, 
                                    PartOfSpeech = "prep" },
                                new Word { Greek = "αὐτῆς", Transliteration = "autēs", Gloss = "itself", 
                                    GrammarCodes = new List<string> { "PRON", "GEN", "F", "S" }, 
                                    PartOfSpeech = "prep" },
                                new Word { Greek = "τῆς", Transliteration = "tēs", Gloss = "the", 
                                    GrammarCodes = new List<string> { "ART", "GEN", "F", "S" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "ἀληθείας", Transliteration = "alētheias", Gloss = "truth", 
                                    GrammarCodes = new List<string> { "N", "GEN", "F", "S" }, 
                                    PartOfSpeech = "n" }
                            },
                            Translation = "by the truth itself"
                        }
                    },
                    Translation = "Demetrius has received a good testimony from everyone, and from the truth itself;"
                },
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "καὶ", Transliteration = "kai", Gloss = "and", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Word { Greek = "ἡμεῖς", Transliteration = "hēmeis", Gloss = "we", 
                            GrammarCodes = new List<string> { "PRON", "NOM", "1P", "P" }, 
                            PartOfSpeech = "prep" },
                        new Word { Greek = "δὲ", Transliteration = "de", Gloss = "also", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Word { Greek = "μαρτυροῦμεν", Transliteration = "martyroumen", Gloss = "testify", 
                            GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "1P", "P" }, 
                            PartOfSpeech = "v" }
                    },
                    Translation = "and we also testify,"
                },
                new Phrase
                {
                    SyntaxCodes = new List<string> { "CAUSAL_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "καὶ", Transliteration = "kai", Gloss = "and", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Word { Greek = "οἶδας", Transliteration = "oidas", Gloss = "you know", 
                            GrammarCodes = new List<string> { "V", "PERF", "ACT", "IND", "2P", "S" }, 
                            PartOfSpeech = "v" },
                        new Word { Greek = "ὅτι", Transliteration = "hoti", Gloss = "that", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "SUBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "ἡ", Transliteration = "hē", Gloss = "the", 
                                    GrammarCodes = new List<string> { "ART", "NOM", "F", "S" }, 
                                    PartOfSpeech = "art" },
                                new Word { Greek = "μαρτυρία", Transliteration = "martyria", Gloss = "testimony", 
                                    GrammarCodes = new List<string> { "N", "NOM", "F", "S" }, 
                                    PartOfSpeech = "n" },
                                new Word { Greek = "ἡμῶν", Transliteration = "hēmōn", Gloss = "of us", 
                                    GrammarCodes = new List<string> { "PRON", "GEN", "1P", "P" }, 
                                    PartOfSpeech = "prep" }
                            },
                            Translation = "our testimony"
                        },
                        new Word { Greek = "ἀληθής", Transliteration = "alēthēs", Gloss = "true", 
                            GrammarCodes = new List<string> { "ADJ", "NOM", "F", "S" }, 
                            PartOfSpeech = "adj" },
                        new Word { Greek = "ἐστιν", Transliteration = "estin", Gloss = "is", 
                            GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "3P", "S" }, 
                            PartOfSpeech = "v" }
                    },
                    Translation = "and you know that our testimony is true."
                },

                // Verse 13
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "NOUN_PHRASE", "OBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "Πολλὰ", Transliteration = "Polla", Gloss = "Many things", 
                                    GrammarCodes = new List<string> { "ADJ", "ACC", "N", "P" }, 
                                    PartOfSpeech = "adj" }
                            },
                            Translation = "many things"
                        },
                        new Word { Greek = "εἶχον", Transliteration = "eichon", Gloss = "I had", 
                            GrammarCodes = new List<string> { "V", "IMPF", "ACT", "IND", "1P", "S" }, 
                            PartOfSpeech = "v" },
                        new Word { Greek = "γράψαι", Transliteration = "grapsai", Gloss = "to write", 
                            GrammarCodes = new List<string> { "V", "AOR", "ACT", "INF" }, 
                            PartOfSpeech = "v" },
                        new Word { Greek = "σοι", Transliteration = "soi", Gloss = "to you", 
                            GrammarCodes = new List<string> { "PRON", "DAT", "2P", "S" }, 
                            PartOfSpeech = "prep" }
                    },
                    Translation = "I had many things to write to you,"
                },
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "ἀλλ᾽", Transliteration = "all'", Gloss = "but", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Word { Greek = "οὐ", Transliteration = "ou", Gloss = "not", 
                            GrammarCodes = new List<string> { "ADV" }, 
                            PartOfSpeech = "prep" },
                        new Word { Greek = "θέλω", Transliteration = "thelō", Gloss = "I am willing", 
                            GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "1P", "S" }, 
                            PartOfSpeech = "v" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PREP_PHRASE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "διὰ", Transliteration = "dia", Gloss = "through", 
                                    GrammarCodes = new List<string> { "PREP" }, 
                                    PartOfSpeech = "prep" },
                                new Word { Greek = "μέλανος", Transliteration = "melanos", Gloss = "ink", 
                                    GrammarCodes = new List<string> { "N", "GEN", "N", "S" }, 
                                    PartOfSpeech = "n" },
                                new Word { Greek = "καὶ", Transliteration = "kai", Gloss = "and", 
                                    GrammarCodes = new List<string> { "CONJ" }, 
                                    PartOfSpeech = "conj" },
                                new Word { Greek = "καλάμου", Transliteration = "kalamou", Gloss = "pen", 
                                    GrammarCodes = new List<string> { "N", "GEN", "M", "S" }, 
                                    PartOfSpeech = "n" }
                            },
                            Translation = "with ink and pen"
                        },
                        new Word { Greek = "σοι", Transliteration = "soi", Gloss = "to you", 
                            GrammarCodes = new List<string> { "PRON", "DAT", "2P", "S" }, 
                            PartOfSpeech = "prep" },
                        new Word { Greek = "γράφειν", Transliteration = "graphein", Gloss = "to write", 
                            GrammarCodes = new List<string> { "V", "PRES", "ACT", "INF" }, 
                            PartOfSpeech = "v" }
                    },
                    Translation = "but I am not willing to write them to you with ink and pen;"
                },

                // Verse 14
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "ἐλπίζω", Transliteration = "elpizō", Gloss = "I hope", 
                            GrammarCodes = new List<string> { "V", "PRES", "ACT", "IND", "1P", "S" }, 
                            PartOfSpeech = "v" },
                        new Word { Greek = "δὲ", Transliteration = "de", Gloss = "but", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Word { Greek = "εὐθέως", Transliteration = "eutheōs", Gloss = "soon", 
                            GrammarCodes = new List<string> { "ADV" }, 
                            PartOfSpeech = "adj" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "INF_PHRASE", "OBJ" },
                            Content = new List<object>
                            {
                                new Word { Greek = "σε", Transliteration = "se", Gloss = "you", 
                                    GrammarCodes = new List<string> { "PRON", "ACC", "2P", "S" }, 
                                    PartOfSpeech = "prep" },
                                new Word { Greek = "ἰδεῖν", Transliteration = "idein", Gloss = "to see", 
                                    GrammarCodes = new List<string> { "V", "AOR", "ACT", "INF" }, 
                                    PartOfSpeech = "v" }
                            },
                            Translation = "to see you soon"
                        }
                    },
                    Translation = "but I hope to see you soon,"
                },
                new Phrase
                {
                    SyntaxCodes = new List<string> { "INDEP_CLAUSE" },
                    Content = new List<object>
                    {
                        new Word { Greek = "καὶ", Transliteration = "kai", Gloss = "and", 
                            GrammarCodes = new List<string> { "CONJ" }, 
                            PartOfSpeech = "conj" },
                        new Phrase
                        {
                            SyntaxCodes = new List<string> { "PREP_PHRASE" },
                            Content = new List<object>
                            {
                                new Word { Greek = "στόμα", Transliteration = "stoma", Gloss = "mouth", 
                                    GrammarCodes = new List<string> { "N", "ACC", "N", "S" }, 
                                    PartOfSpeech = "n" },
                                new Word { Greek = "πρὸς", Transliteration = "pros", Gloss = "to", 
                                    GrammarCodes = new List<string> { "PREP" }, 
                                    PartOfSpeech = "prep" },
                                new Word { Greek = "στόμα", Transliteration = "stoma", Gloss = "mouth", 
                                    GrammarCodes = new List<string> { "N", "ACC", "N", "S" }, 
                                    PartOfSpeech = "n" }
                            },
                            Translation = "face to face"
                        },
                        new Word { Greek = "λαλήσομεν", Transliteration = "lalēsomen", Gloss = "we will speak", 
                            GrammarCodes = new List<string> { "V", "FUT", "ACT", "IND", "1P", "P" }, 
                            PartOfSpeech = "v" }
                    },
                    Translation = "and we will speak face to face."
                },
            };
        }

        public static List<(string Root, string Transliteration, string Gloss, string PartOfSpeech, int Occurrences)> GetVocabulary()
        {
            return new List<(string, string, string, string, int)>
            {
                ("Ὁ", "Ho", "the", "art", 1),
                ("πρεσβύτερος", "presbyteros", "elder", "adj", 1),
                ("Γαΐῳ", "Gaiō", "to Gaius", "n", 1),
                ("τῷ", "tō", "the", "art", 1),
                ("ἀγαπητῷ", "agapētō", "beloved", "adj", 1),
                ("ὃν", "hon", "whom", "pron", 1),
                ("ἐγὼ", "egō", "I", "pron", 1),
                ("ἀγαπῶ", "agapō", "love", "v", 1),
                ("ἐν", "en", "in", "prep", 1),
                ("ἀληθείᾳ", "alētheia", "truth", "n", 1),
                ("Ἀγαπητέ", "Agapēte", "Beloved", "adj", 1),
                ("περὶ", "peri", "concerning", "prep", 1),
                ("πάντων", "pantōn", "all things", "adj", 1),
                ("εὔχομαί", "euchomai", "I pray", "v", 1),
                ("σε", "se", "you", "pron", 1),
                ("εὐοδοῦσθαι", "euodousthai", "to prosper", "v", 1),
                ("καὶ", "kai", "and", "conj", 1),
                ("ὑγιαίνειν", "hygiainein", "to be in health", "v", 1),
                ("καθὼς", "kathōs", "just as", "adv", 1),
                ("εὐοδοῦταί", "euodoutai", "prospers", "v", 1),
                ("σου", "sou", "your", "pron", 1),
                ("ἡ", "hē", "the", "art", 2),
                ("ψυχή", "psychē", "soul", "n", 1),
                ("ἐχάρην", "echarēn", "I rejoiced", "v", 1),
                ("γὰρ", "gar", "for", "conj", 1),
                ("λίαν", "lian", "greatly", "adv", 1),
                ("ἐρχομένων", "erchomenōn", "coming", "v", 1),
                ("ἀδελφῶν", "adelphōn", "brothers", "n", 1),
                ("μαρτυρούντων", "martyrountōn", "testifying", "v", 1),
                ("τῇ", "tē", "the", "art", 1),
                ("σὺ", "sy", "you", "pron", 1),
                ("περιπατεῖς", "peripateis", "walk", "v", 1),
                ("μειζοτέραν", "meizoteran", "greater", "adj", 1),
                ("τούτων", "toutōn", "than these", "pron", 1),
                ("οὐκ", "ouk", "not", "part", 1),
                ("ἔχω", "echō", "I have", "v", 1),
                ("χαράν", "charan", "joy", "n", 1),
                ("ἵνα", "hina", "that", "conj", 1),
                ("ἀκούω", "akouō", "I may hear", "v", 1),
                ("τὰ", "ta", "the", "art", 1),
                ("ἐμὰ", "ema", "my", "adj", 1),
                ("τέκνα", "tekna", "children", "n", 1),
                ("περιπατοῦντα", "peripatounta", "walking", "v", 1),
                ("πιστὸν", "piston", "faithfully", "adj", 1),
                ("ποιεῖς", "poieis", "you do", "v", 1),
                ("ὃ", "ho", "whatever", "pron", 1),
                ("ἐὰν", "ean", "ever", "part", 1),
                ("ἐργάσῃ", "ergasē", "you work", "v", 1),
                ("εἰς", "eis", "for", "prep", 1),
                ("τοὺς", "tous", "the", "art", 1),
                ("ἀδελφοὺς", "adelphous", "brothers", "n", 1),
                ("τοῦτο", "touto", "even", "pron", 1),
                ("ξένους", "xenous", "strangers", "adj", 1),
                ("οἳ", "hoi", "who", "pron", 1),
                ("ἐμαρτύρησάν", "emartyrēsan", "testified", "v", 1),
                ("ἀγάπῃ", "agapē", "love", "n", 1),
                ("ἐνώπιον", "enōpion", "before", "prep", 1),
                ("ἐκκλησίας", "ekklēsias", "church", "n", 1),
                ("οὓς", "hous", "whom", "pron", 1),
                ("καλῶς", "kalōs", "well", "adv", 1),
                ("ποιήσεις", "poiēseis", "you will do", "v", 1),
                ("προπέμψας", "propempsas", "having sent forward", "v", 1),
                ("ἀξίως", "axiōs", "worthily", "adv", 1),
                ("τοῦ", "tou", "of", "art", 1),
                ("θεοῦ", "theou", "God", "n", 1),
                ("ὑπὲρ", "hyper", "for the sake of", "prep", 1),
                ("ὀνόματος", "onomatos", "name", "n", 1),
                ("ἐξῆλθον", "exēlthon", "they went out", "v", 1),
                ("μηδὲν", "mēden", "nothing", "adj", 1),
                ("λαμβάνοντες", "lambanontes", "accepting", "v", 1),
                ("ἀπὸ", "apo", "from", "prep", 1),
                ("τῶν", "tōn", "the", "art", 1),
                ("ἐθνικῶν", "ethnikōn", "Gentiles", "adj", 1),
                ("ἡμεῖς", "hēmeis", "we", "pron", 1),
                ("οὖν", "oun", "therefore", "conj", 1),
                ("ὀφείλομεν", "opheilomen", "ought", "v", 1),
                ("ὑπολαμβάνειν", "hypolambanein", "to support", "v", 1),
                ("τοιούτους", "toioutous", "such men", "pron", 1),
                ("συνεργοὶ", "synergoi", "fellow workers", "adj", 1),
                ("γινώμεθα", "ginōmetha", "we may be", "v", 1),
                ("Ἔγραψά", "Egrapsa", "I wrote", "v", 1),
                ("τι", "ti", "something", "part", 1),
                ("ἐκκλησίᾳ", "ekklēsia", "church", "n", 1),
                ("ἀλλ᾽", "all'", "but", "conj", 1),
                ("ὁ", "ho", "the [one]", "art", 1),
                ("φιλοπρωτεύων", "philoprotueōn", "loving to be first", "v", 1),
                ("αὐτῶν", "autōn", "of them", "prep", 1),
                ("Διοτρέφης", "Diotrephēs", "Diotrephes", "n", 1),
                ("ἐπιδέχεται", "epidechetai", "welcomes", "v", 1),
                ("ἡμᾶς", "hēmas", "us", "prep", 1),
                ("διὰ", "dia", "because of", "prep", 1),
                ("ἔλθω", "elthō", "I come", "v", 1),
                ("ὑπομνήσω", "hypomnēsō", "I will bring to mind", "v", 1),
                ("αὐτοῦ", "autou", "his", "prep", 1),
                ("ἔργα", "erga", "works", "n", 1),
                ("ἃ", "ha", "which", "pron", 1),
                ("ποιεῖ", "poiei", "he does", "v", 1),
                ("λόγοις", "logois", "with words", "n", 1),
                ("πονηροῖς", "ponērois", "wicked", "adj", 1),
                ("φλυαρῶν", "phlyarōn", "gossiping against", "v", 1),
                ("μὴ", "mē", "not", "prep", 1),
                ("ἀρκούμενος", "arkoumenos", "being content", "v", 1),
                ("ἐπὶ", "epi", "with", "prep", 1),
                ("τούτοις", "toutois", "these things", "adv", 1),
                ("οὔτε", "oute", "neither", "conj", 1),
                ("αὐτὸς", "autos", "he himself", "prep", 1),
                ("βουλομένους", "boulomenous", "desiring [to do so]", "v", 1),
                ("κωλύει", "kōlyei", "he hinders", "v", 1),
                ("ἐκ", "ek", "out of", "prep", 1),
                ("τῆς", "tēs", "the", "art", 1),
                ("ἐκβάλλει", "ekballei", "he throws [them] out", "v", 1),
                ("μιμοῦ", "mimou", "imitate", "v", 1),
                ("τὸ", "to", "the", "art", 1),
                ("κακὸν", "kakon", "evil", "adj", 1),
                ("ἀλλὰ", "alla", "but", "conj", 1),
                ("ἀγαθόν", "agathon", "good", "adj", 1),
                ("ἀγαθοποιῶν", "agathopoiōn", "doing good", "v", 1),
                ("ἐστιν", "estin", "is", "v", 5),
                ("κακοποιῶν", "kakopoiōn", "doing evil", "v", 1),
                ("οὐχ", "ouch", "not", "prep", 1),
                ("ἑώρακεν", "heōraken", "has seen", "v", 1),
                ("τὸν", "ton", "the", "art", 1),
                ("θεόν", "theon", "God", "n", 1),
                ("Δημητρίῳ", "Dēmētriō", "to Demetrius", "n", 1),
                ("μεμαρτύρηται", "memartyrētai", "it is testified", "v", 1),
                ("ὑπὸ", "hypo", "by", "prep", 1),
                ("αὐτῆς", "autēs", "itself", "prep", 1),
                ("ἀληθείας", "alētheias", "truth", "n", 1),
                ("δὲ", "de", "also", "conj", 1),
                ("μαρτυροῦμεν", "martyroumen", "testify", "v", 1),
                ("οἶδας", "oidas", "you know", "v", 1),
                ("ὅτι", "hoti", "that", "conj", 1),
                ("μαρτυρία", "martyria", "testimony", "n", 1),
                ("ἡμῶν", "hēmōn", "of us", "prep", 1),
                ("ἀληθής", "alēthēs", "true", "adj", 1),
                ("Πολλὰ", "Polla", "Many things", "adj", 1),
                ("εἶχον", "eichon", "I had", "v", 1),
                ("γράψαι", "grapsai", "to write", "v", 1),
                ("σοι", "soi", "to you", "prep", 1),
                ("οὐ", "ou", "not", "prep", 1),
                ("θέλω", "thelō", "I am willing", "v", 1),
                ("μέλανος", "melanos", "ink", "n", 1),
                ("καλάμου", "kalamou", "pen", "n", 1),
                ("γράφειν", "graphein", "to write", "v", 1),
                ("ἐλπίζω", "elpizō", "I hope", "v", 1),
                ("εὐθέως", "eutheōs", "soon", "adj", 1),
                ("ἰδεῖν", "idein", "to see", "v", 1),
                ("στόμα", "stoma", "mouth", "n", 1),
                ("πρὸς", "pros", "to", "prep", 1),
                ("λαλήσομεν", "lalēsomen", "we will speak", "v", 1),
            };
        }
    }
}
